# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Cypress Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test_editor:
    name: Test

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install
      run: npm install

    - name: Create DB
      run: npm run init

    - name: Build
      run: npm run dev &

    - name: Test Editor
      run: npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }}
